services:
  accounts:
    image: "faizalabdrahman/accounts:0.0.1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - simple-bank
networks:
  simple-bank:
    driver: "bridge"