spring:
  application:
    name: "configserver"
  profiles:
    # profile used to read from classpath
    # active: native
    # profile used to read config from git
    active: git
  cloud:
    config:
      server:
        native:
          # read config from path location
          # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/faizalabdrahman/spring-simple-bank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    stream:
      username: "guest"
      password: "guest"

encrypt:
  key: "CY8nu6Z3k9UeSajYhzN0wpAPuSq2ENML"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"